<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Customer\Block\Form\Edit $block */
/* @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div class="block block-addresses-list">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Two Factor Authentication')); ?></strong></div>
    <div class="block-content">
        <p class="empty"><?= $block->escapeHtml(__('Status')); ?>: <strong><?= $block->isOtpEnabled() ? $block->escapeHtml(__('Enabled')) : $block->escapeHtml(__('Disabled')); ?></strong></p>
        <?php if ($block->isOtpEnabled()): ?>
            <div class="empty message success">
                <span>You have already activate 2 Factor Authentication.</span>
            </div>
        <?php else: ?>
            <div class="empty message warning">
                <span>To protect your account, you can use Google Authenticator / Microsoft Authenticator / 2FA Authenticator / etc to have additional validation on login page.</span>
            </div>
        <?php endif; ?>
    </div>
</div>

<div class="actions-toolbar">
    <div class="primary">
        <?php if ($block->isOtpEnabled()): ?>
            <a href="<?= $block->escapeHtmlAttr($this->urlInterface->getUrl('*/*/disable')); ?>" alt="" class="action primary add"><span><?= $block->escapeHtml(__('Disable Login Security')); ?></span></a>
        <?php else : ?>
            <a href="<?= $block->escapeHtmlAttr($this->urlInterface->getUrl('*/*/*/enable')); ?>" alt="" class="action primary add"><span><?= $block->escapeHtml(__('Enable Login Security')); ?></span></a>
        <?php endif; ?>
    </div>
</div>

<?php return; ?>

<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')); ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')); ?>"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey'); ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Two Factor Authentication')); ?></span></legend><br>
        <?= $block->getLayout()->createBlock(Name::class)->setObject($block->getCustomer())->toHtml(); ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class); ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class); ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class); ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml(); ?>
        <?php endif; ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml(); ?>
        <?php endif; ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml(); ?>
        <?php endif; ?>
        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Email')); ?>" class="checkbox" />
            <label class="label" for="change-email">
                <span><?= $block->escapeHtml(__('Change Email')); ?></span>
            </label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1"
                   title="<?= $block->escapeHtmlAttr(__('Change Password')); ?>"
                <?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password">
                <span><?= $block->escapeHtml(__('Change Password')); ?></span>
            </label>
        </div>
        <?= $block->getChildHtml('fieldset_edit_info_additional'); ?>
    </fieldset>

</form>