<?php
/**
 * Copyright © Fiko Borizqy, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var \Fiko\CustomerTwoFactorAuth\Block\LoginSecurity $block
 */
?>
<div class="block block-addresses-list">
    <div class="block-title"><strong><?= $escaper->escapeHtml(__('Two Factor Authentication')); ?></strong></div>
    <div class="block-content">
        <p class="empty">
            <?= $escaper->escapeHtml(__('Status')); ?>:
            <strong>
                <?= $block->isOtpEnabled() ? $escaper->escapeHtml(__('Enabled')) : $escaper->escapeHtml(__('Disabled')); ?>
            </strong>
        </p>
        <?php if ($block->isOtpEnabled()): ?>
            <div class="empty message success">
                <span><?= $escaper->escapeHtml(__('You have already activate 2 Factor Authentication.')); ?></span>
            </div>
        <?php else: ?>
            <div class="empty message warning">
                <span>
                    <?= $escaper->escapeHtml(__('To protect your account, you can use Google Authenticator / Microsoft Authenticator / 2FA Authenticator / etc to have additional validation on login page.')); ?>
                </span>
            </div>
        <?php endif; ?>
    </div>
</div>

<div class="actions-toolbar">
    <div class="primary">
        <?php if ($block->isOtpEnabled()): ?>
            <a href="<?= $escaper->escapeHtmlAttr($block->getUrl('*/*/disable')); ?>"
                alt="" 
                class="action primary add"
            >
                <span><?= $escaper->escapeHtml(__('Disable Login Security')); ?></span>
            </a>
        <?php else: ?>
            <a href="<?= $escaper->escapeHtmlAttr($block->getUrl('*/*/enable')); ?>"
                alt=""
                class="action primary add"
            >
                <span><?= $escaper->escapeHtml(__('Enable Login Security')); ?></span>
            </a>
        <?php endif; ?>
    </div>
</div>