<?php
/**
 * Copyright © Fiko Borizqy, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var \Fiko\CustomerTwoFactorAuth\Block\LoginSecurity $block
 */
?>

<form class="form form-edit-account" action="<?= $escaper->escapeUrl($block->getUrl('*/*/enablepost')); ?>"
      method="post" id="form-validate" autocomplete="off" data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey'); ?>
        <legend class="legend">
            <span><?= $escaper->escapeHtml(__('Enable Two Factor Authentication')); ?></span>
        </legend><br>

        <div class="field">
            <div class="message info">
                <span>
                    <?= $escaper->escapeHtml('Scan this QR Code using Google Authenticator / Microsoft Authenticator / 2FA Authenticator / etc to secure your account.'); ?>
                </span>
            </div>
            <center><img src="<?= $escaper->escapeUrl($block->getUrl('*/account/otpqrcodeimage')); ?>" alt="" /></center>
        </div>

        <div class="field">
            <i>
                <?= __(
                    'if you can not scan the QR Code above, copy this code to your authenticator app : %1',
                    "<strong>{$block->authHelper->getCustomerOtpSecret()}</strong>"
                ); ?>
            </i>
        </div>

        <div class="field required">
            <label class="label" for="otp-token">
                <span><?= $escaper->escapeHtml(__('Confirmation Code')); ?></span>
            </label>
            <div class="control">
                <input type="text" id="otp-token" name="otp-token" 
                       title="<?= $escaper->escapeHtmlAttr(__('Confirmation Code')); ?>"
                       class="input-text required-entry" data-validate="{required:true}" aria-required="true" 
                       required data-mage-init='{"mage/trim-input":{}}'>
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset info"></fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="Save">
                <span><?= $escaper->escapeHtml(__('Save')); ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action" href="<?= $escaper->escapeUrl($block->getUrl('*/*')); ?>">
                <span>&larr; <?= $escaper->escapeHtml(__('Cancel')); ?></span>
            </a>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
